feature/added admin panel and user crud
Jakub-Klejczyk/Strefa_Wolnosci pull request #1
Opened 2023-02-25 22:29 UTC by Jakub-Klejczyk

Starting point for admin panel. Already created crud for user and basic layout.

2023-02-26 09:55 UTC, BrittleHeart requested changes
posprawdzaj sobie. Jak będziesz miał pytania to wal. Później dodamy pozostałe poprawki

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +    }
1. Niezgodność z standardem PSR
Klamry poniżej metody.

2. kontroler nie powinien być odpowiedzialny za wyciąganie danych z bazy. Do tego służy repozytorium. Poczytaj jak go wdrożyć do Laravela

3. Nie będziesz potrzebować paginacji? Bo jeżeli tak, wypada to dodać

4 Zamiast tego response()->json() 
Powinieneś zwrócić resource 

https://laravel.com/docs/10.x/eloquent-resources

Łatwiej będzie to czytać

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +    }
To samo tutaj, logika do repo
Dlaczego nie ma żadnej podpowiedzi tylko zwykle tworzenie w dodatki z bezużyteczna zmienna? 

Dodać zwrotkę, stworzyć repo
Dodać customowy request

```bash
php artisan make:request NewsCreateRequest
```

Kolejna rzecz, nie wiem skąd wziąłeś request->post(). Niemniej, nie używa się tego, jak już request->validated()

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +    }
Do resource

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +    }
To samo co w store, użyć metody update zamiast fill, do repo logika tworzenia 
I jak już to return new JsonRepnse z przestrzeni Facades

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +    }
A co jeżeli cis się stanie i newsa nie będzie? 
To samo co wyżej

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/SectionsController.php
> +    }
Ładny c/p, ale to samo co wyżej. Poza tym, jak używasz all'a, to albo all, albo jeszcze metoda only
Nie rozumiem tylko w czyn przeszkadza Ci ten created_at - przydaje się na front'cie

2023-02-26 09:55 UTC, BrittleHeart commented on app/Http/Controllers/UserController.php
> +        ]);
Tutaj jest sprawdzenie a w news'ach nie ? Dodać customowy request

2023-02-26 09:55 UTC, BrittleHeart commented on database/seeders/DatabaseSeeder.php
> +         \App\Models\User::factory(1)->create();
1 jest wartością domyślna wiec możesz to ominąć

2023-02-26 09:55 UTC, BrittleHeart commented on resources/scss/app.scss
> +$light-red: rgb(227, 36, 36);
To innego modułu, stwórz sobie moduł colors i zaimportuj

2023-02-26 09:55 UTC, BrittleHeart commented on resources/scss/app.scss
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap");
Fonty to modułu fonts

2023-02-26 09:55 UTC, BrittleHeart commented on resources/scss/app.scss
> +    }
Do modułu mixins

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/App.vue
> +<script script lang="ts">
? <script script>? 
Przejęzyczenie zapewne, wywalić jedno z nich

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/App.vue
> +    <RouterView />
Zgodnie z dokumentacją powinno to wyglądać 
```vue
<router-view>
```

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/components/users_admin/UserSection.vue
> +                });
Jezus Maryja, nie rób tak
Poczytaj sobie jeszcze raz jak działa async await :-: i nie rób tak

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/components/users_admin/UserSection.vue
> +    },
Dlaczego to nie jest w asyncu?

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/components/users_admin/UserSection.vue
> +        },
??

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/components/users_admin/UserSection.vue
> +    <UserForm
Do poprawy nezewnictwo komponentow

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/router/index.ts
>      ],
routes do innego pliku z predefiniowane tablica

2023-02-26 09:55 UTC, BrittleHeart commented on resources/ts/views/LandingView.vue
> +<script script lang="ts">
To samo tu. Co to do cholery jest :-:

2023-02-26 21:19 UTC, Jakub-Klejczyk commented on resources/ts/App.vue
> +<script script lang="ts">
yup, miss powielany potem przez kopiuj wklej przy tworzeniu kolejnych komponentów

2023-02-26 21:20 UTC, Jakub-Klejczyk commented on resources/ts/components/users_admin/UserSection.vue
> +        },
chce, żeby zmienna mi się wyczyściła po 10sec, żeby mi napis nie wisiał na ekranie. Nie ok?

2023-02-26 21:20 UTC, Jakub-Klejczyk commented on resources/ts/components/users_admin/UserSection.vue
> +    <UserForm
tzn? Bardziej coś w stylu 'DeleteModeWindow'?

2023-02-26 21:21 UTC, Jakub-Klejczyk commented on resources/ts/router/index.ts
>      ],
co to znaczy predefiniowana tablica?

2023-02-27 12:28 UTC, BrittleHeart commented on resources/ts/components/users_admin/UserSection.vue
> +    <UserForm
Bardziej coś w stylu
```suggestion
    <delete-mode
        v-if="deleteMode == true"
        :text="'użytkownika'"
        :deleteObject="() => deleteUser(user.id)"
        @close-delete-mode="() => (deleteMode = false)"
    />
    <user-form>
```

2023-02-27 12:30 UTC, BrittleHeart commented on resources/ts/router/index.ts
>      ],
dokładnie to samo co masz tutaj, tylko przekopiuj to do innego pliku, zrób z niego moduł
i zrób coś w stylu

```ts
const routes: Route[] = [
  {
        path: "/admin",
        name: "admin",
        component: AdminPanelView,
  },
```

2023-02-27 12:32 UTC, BrittleHeart commented on resources/ts/components/users_admin/UserSection.vue
> +        },
ale po co chcesz ja czyścić?

2023-02-27 16:18 UTC, Jakub-Klejczyk commented on resources/ts/components/users_admin/UserSection.vue
> +        },
reponse to tekst, który otrzymuje z controllera po update/delete/store usera. Wyświetlam ten string na ekranie jako komunikat, np 'Dodano użytkownika' i chce, żeby po jakimś czasie ten napis zniknął z ekranu i nie wisiał tam do kolejnego odświeżenia lub otrzymania nowego response.

2023-03-08 10:14 UTC, BrittleHeart requested changes
Popoprawiaj wszędzie błędy, powywalaj to bezużyteczne i jak będziesz miał pytania to wal

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +        return response($news);
bezużyteczna zmienna. Zwróć samą kolekcje

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +        $file = $request->file('img');
Wypada sprawdzić, czy plik w ogóle stnieje, jakie ma rozszerzenie itp

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +            'message' => $file
return new \Illuminate\Support\Facades\JsonResponse(..)

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +        // return ['message'=>'Zaktualizowano wpis!'];
jak nie używasz, do wyjebania

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
>          return response()->json($news);
Właśnie to robi, Laravel wysyła tutaj poprawne zapytanie do Eloquent'a. Tylko musisz to poprawnie w routingu dać

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +
Teraz, to żeś dojebał. 

Napisz tą metodę od nowa, używając wyłącznie
```php
public function update(NewsUpdateRequest $request, News $news /* albo int $id */)
{}
```
Poza tym, nie $request->validate

tylko validated bez parametrów

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/NewsController.php
> +        return ['message'=>'Usunięto wpis!'];
Ja wiem, że Laravel sam parsuje takie coś, ale weź użyj tu json response albo czegokolwiek

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/SectionsController.php
> +        return response($sections);
Zmienna bezużyteczna

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/SectionsController.php
> +        return ['message'=>'Dodano nową sekcję!'];
To samo tu. Skąd Ty to bierzesz

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/SectionsController.php
>      }
To samo tu

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/SectionsController.php
>      }
Miałeś dobrze, już masz źle

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/UserController.php
> +        $request['password'] = bcrypt($request['password']);
```php
$request->input(),

Hash::make()
```

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/UserController.php
>          $formFields = $request->validate([
Do poprawy

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Controllers/UserController.php
>          $request->session()->invalidate();
A skąd pewność, że sesja istnieje? 
Skąd Ty te zapisy bierzesz?

2023-03-08 10:14 UTC, BrittleHeart commented on app/Http/Resources/SectionsCollection.php
> +}
Czytałeś docsy?
```php
<?php
 
namespace App\Http\Resources;
 
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;
 
class UserCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @return array<int|string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'data' => $this->collection,
            'links' => [
                'self' => 'link-value',
            ],
        ];
    }
}
```

2023-03-08 10:14 UTC, BrittleHeart commented on resources/ts/components/posts_admin/PostsSection.vue
> +        },
mówiłem, że then do wyjebania

2023-03-08 10:14 UTC, BrittleHeart commented on resources/ts/components/sections_admin/SectionsForm.vue
> +    <form action="" @submit.prevent="() => onObject()">
po co Ci tu callback?

2023-03-08 14:59 UTC, BrittleHeart requested changes

2023-03-08 14:59 UTC, BrittleHeart commented on app/Http/Requests/NewsDeleteRequest.php
> +            'id' => 'nullable',
Jak id może być nullable ? WHAT the fuck

2023-03-24 07:08 UTC, BrittleHeart requested changes
Masz do zmiany kilka rzeczy, czasem poważniejszych czasem mniej

2023-03-24 07:08 UTC, BrittleHeart commented on app/Http/Requests/UserAuthenticateRequest.php
> +            'password' => 'required|min:6'
dlaczego nie ma maxa? Dlaczego nie ma potwierdzenia?

2023-03-24 07:08 UTC, BrittleHeart commented on app/Models/User.php
>      ];
Jezus maryja, nie rób tak. Przywróć te password do hidden

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/posts_admin/PostsForm.vue
> +<script script lang="ts">
Dalej tego nie poprawiłeś

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/posts_admin/PostsForm.vue
> +        object: { type: Object, required: true },
Jaki kurwa object?

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/posts_admin/PostsForm.vue
> +@import "../../../scss/app.scss";
@/ = src/

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/posts_admin/PostsSection.vue
> +            const data = new FormData();
const formDdata

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/posts_admin/PostsSection.vue
> +                        data: data,
jeżeli zmienna posiada te same właściwości co argument, możesz olać named property

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/sections_admin/SectionsForm.vue
> +        text: { type: String, required: true },
Same here

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/components/sections_admin/SectionsSection.vue
> +                        data: this.section,
Ty sie zdecyduj z tym form data

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/router/routes.ts
> +import Route from "../types/Route";
Nie type tylko interface

2023-03-24 07:08 UTC, BrittleHeart commented on resources/ts/types/Post.ts
> +type Post = {
Same here, nie type tylko interface

2023-04-07 11:32 UTC, merged